### ISSUE TITLE
appbundle 1.5.0 package import errors on Unity 2018.4.10f1

### ISSUE THREAD

**Issue by JordanEllapin** [google/play-unity-plugins#123]
Hi!

The release page says the plugins won't compile below Unity 2018.2 but even on 2018.4 it does not. The erros come from appbundle scripts only.

"Assets\GooglePlayPlugins\com.google.android.appbundle\Editor\Scripts\Bundletool.cs(46,54): error CS1983: The return type of an async method must be void, Task or Task<T>"

"Assets\GooglePlayPlugins\com.google.android.appbundle\Editor\Scripts\Internal\AppBundlePublisher.cs(80,54): error CS1983: The return type of an async method must be void, Task or Task<T>"

"Assets\GooglePlayPlugins\com.google.android.appbundle\Editor\Scripts\Internal\BuildTools\AppBundleBuilder.cs(404,13): error CS0433: The type 'TaskCompletionSource<T>' exists in both 'Unity.Tasks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'"

The 1.4.0 works but like the docs say it was not compatible below 2018.2 I was wondering if I needed to enable or disable some settings to make it work with 1.5.0.

Thank you!

**Comment by jamcohen** [comment]
Hi Jordan,

Thanks for posting this issue.

v1.5.0 includes code that relies on .NET 4.5 features (async/await and TaskCompletionSource), but it's in an #ifdef block and shouldn't be included unless your project's "API Compatibility level" is set to ".NET 4.X Equivalent".

Could you share your full Unity version (e.g. 2018.4.19f1)?
In Player Settings -> Other Settings, what is your "API Compatibility level" set to?
Also, are you using any Firebase plugins?

If your "API Compatibility level" is set to ".NET 4.X Equivalent", make sure you've downloaded the dotnet4 version of your Firebase plugin, rather than the dotnet3 version.

The dotnet3 version includes Unity.Task which causes name collision errors if other code tries to use the built-in System.Threading.Tasks.

**Comment by jamcohen** [comment]
@JordanEllapin, I'm closing this issue, but feel free to reopen it if the suggested fix didn't work for you.
