### ISSUE TITLE
Crash at Android 12

### ISSUE THREAD

**Issue by ByvAntonRybak** [google/play-unity-plugins#187]
Hello
I'm now experiencing crash on android devices with Android 12 only.

thread.cc:2372] Throwing new exception 'No interface method getPackStates(Ljava/util/List;)Lcom/google/android/play/core/tasks/Task; in class Lcom/google/android/play/core/assetpacks/AssetPackManager; or its super classes (declaration of 'com.google.android.play.core.assetpacks.AssetPackManager' appears in base.apk!classes2.dex)' with unexpected pending exception: java.lang.NoSuchMethodError: No interface method getPackStates(Ljava/util/List;)Lcom/google/android/play/core/tasks/Task; in class Lcom/google/android/play/core/assetpacks/AssetPackManager; or its super classes (declaration of 'com.google.android.play.core.assetpacks.AssetPackManager' appears in base.apk!classes2.dex)
    thread.cc:2372]   at void com.unity3d.player.AssetPackManagerWrapper.getAssetPackStates(java.lang.String[], com.unity3d.player.IAssetPackManagerStatusQueryCallback) ((null):-1)
    thread.cc:2372]   at void com.unity3d.player.AssetPackManagerWrapper.getAssetPackState(java.lang.String, com.unity3d.player.IAssetPackManagerStatusQueryCallback) ((null):-1)
    thread.cc:2372]   at boolean com.unity3d.player.UnityPlayer.nativeRender() ((null):-2)
    thread.cc:2372]   at boolean com.unity3d.player.UnityPlayer.access$300(com.unity3d.player.UnityPlayer) ((null):-1)
    thread.cc:2372]   at boolean com.unity3d.player.UnityPlayer$e$1.handleMessage(android.os.Message) ((null):-1)
    thread.cc:2372]   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
    thread.cc:2372]   at boolean android.os.Looper.loopOnce(android.os.Looper, long, int) (Looper.java:226)
    thread.cc:2372]   at void android.os.Looper.loop() (Looper.java:313)
    thread.cc:2372]   at void com.unity3d.player.UnityPlayer$e.run() ((null):-1)
    thread.cc:2372] 

Crash is occurring at second launch of game. After Build&Run all is working perfectly, but after each next reload - crash.
Clearing app cache helps one time, at second time after clear game crashing again.

I'm using Asset Delivery system only from pack and without it all works just fine

**Comment by maxpushkarev** [comment]
the same issue, please help

**Comment by maxpushkarev** [comment]
@ByvAntonRybak  try to downgrade plugins to 1.7.0 version. this helped me to overcome the same crush

**Comment by ByvAntonRybak** [comment]
@maxpushkarev And yes, it helped. No more crashes with old monolithic library.

**Comment by Arivval** [comment]
Hi,

Thanks for reporting this issue. The latest version of Play Core Java libraries includes breaking changes, which requires a [migration process](https://developer.android.com/guide/playcore#common_migration_steps) on the wrapper side. We've identified that this issue should be because play-unity-plugins 1.8.0 bumped the Play Core Java libraries [to 2.0.0](https://github.com/google/play-unity-plugins/commit/7295d55dd7a5a2db221870668410443c873366bf), while Unity's own AssetPackManagerWrapper implementation is still based on pre-2.0.0 Play Core APIs.

We'll be working on a fix to address this issue. In the meanwhile, please depend on 1.7.0 to avoid this issue, and sorry for any inconveniences.

Thanks
John

**Comment by acristo76** [comment]
thanks for the workaround. Will do that and hopefully there will be a fix soon...

**Comment by shawnzhang** [comment]
The issue still happened in play-unity-plugins 1.8.1.
And if possible please make tutorial how to downgrade to play.core 1.7.0.
I try to download from 'History' but I don't know how to download whole folder.

currently I got same issue from catlog ("adb catlog -s Unity"):
`09-18 12:37:41.571  5855  5888 E Unity   : JNI:MountObbs:java.lang.NoSuchMethodError: No interface method getPackStates(Ljava/util/List;)Lcom/google/android/play/core/tasks/Task; in class Lcom/google/android/play/core/assetpacks/AssetPackManager; or its super classes (declaration of 'com.google.android.play.cor
09-18 12:37:41.782  5855  5855 I Unity   : onPause`

Regards.

**Comment by RoshanMethod** [comment]
@shawnzhang  did you find out on how to downgrade to 1.7.0?

**Comment by SalihKyc** [comment]
A problem I've been dealing with for days, I'm in a situation where I've tried upgrading or downgrading many versions and can't get results. Here PAD 1.7.0 is said to be running. The problem with aab I uploaded to play store with version 1.7.0 is "We detected that this app is using an unsupported version of Play billing. Please upgrade to Billing Library 4 or newer to publish this app." I'm getting a warning. I am getting gradle errors with Unity In App Purchase version 4.1. If anyone knows a method, please share. I'm so bored now.

**Comment by Arivval** [comment]
Hi @SalihKyc. I'm sorry to hear about this issue. Could you please try to retrieve Play Asset Delivery 1.7.0 package through the archives in [this page](https://developers.google.com/unity/archive#play_asset_delivery)? The [deprecated Play Billing plugin](https://github.com/google/play-unity-plugins/tree/master/GooglePlayPlugins/com.google.play.billing) is not included in that package, so it should make the Play Console warning go away.

**Comment by hashBini** [comment]
Hi @Arivval, I am also facing the same issue as mentioned in the topic. Crash occurs for me on the start of the game, the game doesn't even launch at all. I am using PAD 1.8.0, and also, I am also using Firebase for unity 8.10.0. Are these creating conflict with each other? 
Also, regarding downgrading to 1.7.0, what would be the proper method? Should I just import the package and replace the 1.8.0 files or completely delete 1.8.0 files and replace them with 1.7.0? 

My crash starts with this: 

`2022/09/24 15:57:57.414 31953 1510 Fatal xyz.abc runtime.cc:675] Runtime aborting...
2022/09/24 15:57:57.414 31953 1510 Fatal xyz.abc runtime.cc:675] All threads:
2022/09/24 15:57:57.414 31953 1510 Fatal xyz.abc runtime.cc:675] DALVIK THREADS (27):
2022/09/24 15:57:57.414 31953 1510 Fatal xyz.abc runtime.cc:675] "UnityMain" prio=5 tid=5 Runnable
2022/09/24 15:57:57.414 31953 1510 Fatal xyz.abc runtime.cc:675]   | group="" sCount=0 ucsCount=0 flags=2 obj=0x13917f00 self=0xb400007b186f7c00
2022/09/24 15:57:57.414 31953 1510 Fatal xyz.abc runtime.cc:675]   | sysTid=1510 nice=0 cgrp=default sched=0/0 handle=0x7b2ab0ecb0
2022/09/24 15:57:57.414 31953 1510 Fatal xyz.abc runtime.cc:675]   | state=R schedstat=( 20613956 11992710 40 ) utm=0 stm=2 core=7 HZ=100
2022/09/24 15:57:57.414 31953 1510 Fatal xyz.abc runtime.cc:675]   | stack=0x7b2aa0b000-0x7b2aa0d000 stackSize=1039KB
2022/09/24 15:57:57.414 31953 1510 Fatal xyz.abc runtime.cc:675]   | held mutexes= "abort lock" "mutator lock"(shared held)
`

And I get this same error as the title some logs down: 

`2022/09/24 15:57:57.502 1370 1370 Error ORMS_HAL open /sys/devices/platform/soc/soc:oplus-omrg/oplus-omrg0/ruler_enable failed(No such file or directory)
2022/09/24 15:57:57.502 1370 1370 Error ORMS_HAL open /sys/devices/platform/soc/soc:oplus-omrg/oplus-omrg0/ruler_enable failed(No such file or directory)
2022/09/24 15:57:57.507 5589 1577 Info KeyboardDefManager KeyboardDefManager.lambda$loadKeyboardDef$2():393 parsing keyboard def from xml failed or task was canceled.
2022/09/24 15:57:57.511 1415 1415 Debug OplusMovieIdle updateLayerStacks,mOmiSupport is not supoort
2022/09/24 15:57:57.511 1370 1370 Error ORMS_HAL open /sys/devices/platform/soc/soc:oplus-omrg/oplus-omrg0/ruler_enable failed(No such file or directory)
2022/09/24 15:57:57.524 1415 1415 Debug OplusMovieIdle updateLayerStacks,mOmiSupport is not supoort
2022/09/24 15:57:57.524 31953 1510 Error CRASH Tombstone written to: /storage/emulated/0/Android/data/in.xyz.abc/files/tombstone_01
2022/09/24 15:57:57.525 31953 1510 Fatal xyz.abc thread.cc:2468] No pending exception expected: java.lang.NoSuchMethodError: No interface method getPackStates(Ljava/util/List;)Lcom/google/android/play/core/tasks/Task; in class Lcom/google/android/play/core/assetpacks/AssetPackManager; or its super classes (declaration of 'com.google.android.play.core.assetpacks.AssetPackManager' appears in /data/app/~~wE8S_MN93DsJ-0MkwnXvgg==/in.xyz.abc-MUXbrqRNi7zfF_j3kqx3cQ==/base.apk)
`

**Comment by duong730** [comment]
> Hi @Arivval, I am also facing the same issue as mentioned in the topic. Crash occurs for me on the start of the game, the game doesn't even launch at all. I am using PAD 1.8.0, and also, I am also using Firebase for unity 8.10.0. Are these creating conflict with each other? Also, regarding downgrading to 1.7.0, what would be the proper method? Should I just import the package and replace the 1.8.0 files or completely delete 1.8.0 files and replace them with 1.7.0?
> 
> My crash starts with this:
> 
> `2022/09/24 15:57:57.414 31953 1510 Fatal xyz.abc runtime.cc:675] Runtime aborting... 2022/09/24 15:57:57.414 31953 1510 Fatal xyz.abc runtime.cc:675] All threads: 2022/09/24 15:57:57.414 31953 1510 Fatal xyz.abc runtime.cc:675] DALVIK THREADS (27): 2022/09/24 15:57:57.414 31953 1510 Fatal xyz.abc runtime.cc:675] "UnityMain" prio=5 tid=5 Runnable 2022/09/24 15:57:57.414 31953 1510 Fatal xyz.abc runtime.cc:675] | group="" sCount=0 ucsCount=0 flags=2 obj=0x13917f00 self=0xb400007b186f7c00 2022/09/24 15:57:57.414 31953 1510 Fatal xyz.abc runtime.cc:675] | sysTid=1510 nice=0 cgrp=default sched=0/0 handle=0x7b2ab0ecb0 2022/09/24 15:57:57.414 31953 1510 Fatal xyz.abc runtime.cc:675] | state=R schedstat=( 20613956 11992710 40 ) utm=0 stm=2 core=7 HZ=100 2022/09/24 15:57:57.414 31953 1510 Fatal xyz.abc runtime.cc:675] | stack=0x7b2aa0b000-0x7b2aa0d000 stackSize=1039KB 2022/09/24 15:57:57.414 31953 1510 Fatal xyz.abc runtime.cc:675] | held mutexes= "abort lock" "mutator lock"(shared held) `
> 
> And I get this same error as the title some logs down:
> 
> `2022/09/24 15:57:57.502 1370 1370 Error ORMS_HAL open /sys/devices/platform/soc/soc:oplus-omrg/oplus-omrg0/ruler_enable failed(No such file or directory) 2022/09/24 15:57:57.502 1370 1370 Error ORMS_HAL open /sys/devices/platform/soc/soc:oplus-omrg/oplus-omrg0/ruler_enable failed(No such file or directory) 2022/09/24 15:57:57.507 5589 1577 Info KeyboardDefManager KeyboardDefManager.lambda$loadKeyboardDef$2():393 parsing keyboard def from xml failed or task was canceled. 2022/09/24 15:57:57.511 1415 1415 Debug OplusMovieIdle updateLayerStacks,mOmiSupport is not supoort 2022/09/24 15:57:57.511 1370 1370 Error ORMS_HAL open /sys/devices/platform/soc/soc:oplus-omrg/oplus-omrg0/ruler_enable failed(No such file or directory) 2022/09/24 15:57:57.524 1415 1415 Debug OplusMovieIdle updateLayerStacks,mOmiSupport is not supoort 2022/09/24 15:57:57.524 31953 1510 Error CRASH Tombstone written to: /storage/emulated/0/Android/data/in.xyz.abc/files/tombstone_01 2022/09/24 15:57:57.525 31953 1510 Fatal xyz.abc thread.cc:2468] No pending exception expected: java.lang.NoSuchMethodError: No interface method getPackStates(Ljava/util/List;)Lcom/google/android/play/core/tasks/Task; in class Lcom/google/android/play/core/assetpacks/AssetPackManager; or its super classes (declaration of 'com.google.android.play.core.assetpacks.AssetPackManager' appears in /data/app/~~wE8S_MN93DsJ-0MkwnXvgg==/in.xyz.abc-MUXbrqRNi7zfF_j3kqx3cQ==/base.apk) `

Unity 2021.3.12 and PAD 1.81 still get this crash. Do you know how to downgrade to vs 1.7.0? Can you tell me please.

**Comment by isurfraz** [comment]
how is it that the entire PAD system is unusable in unity for 6 months? 1.8+ does not work - is somebody going to address this?

**Comment by Trunksome** [comment]
any updates on this? @Arivval is there an ETA for a new version that fixes the issue?

**Comment by NightQnEarth** [comment]
We faced with this issue too after updating to 1.8.1 version of plugins.

**Comment by TrueRaider** [comment]
Maybe fixed in 2023.1.0 https://issuetracker.unity3d.com/issues/crash-when-using-unity-built-in-play-asset-delivery-integration-together-with-play-core-libraries-2-dot-0-0-plus

**Comment by hashBini** [comment]
So, I had finally fixed this issue some time ago, and am sharing my solution here. 
Basically what it boils down is to have compatible versions of PAD plugin, Unity and Firebase (if you are using it).
I tried to mix and match various version of Unity 2019, PAD, and firebase, and then it finally worked.

Unity - 2019.4.40f1
Firebase - 8.10.0 (for all the modules I was using)
PAD - 1.7.0 

What I think is that Firebase and PAD are conflicting with each other in some versions. So you'll need to make sure that you have compatible versions and it will work.

**Comment by Watcher3056** [comment]
+1 Need fix. Why we should to use unity 2023.1.0 beta? We cannot just upgrade out projects on such unstable unity release!

**Comment by GPavlioudakis** [comment]
Hi everyone. I'm facing the same issue in my case. I use Unity 2022.3.2f1. The issue is that I haven't installed PAD. Is it pre installed? And how do I downgrade it to 1.7 ?

**Comment by RotcivOcnarb** [comment]
Also having the same issue with PAD 1.8.2, i didn't even configure anything in the project, just installed the SDK and builded the game that was working, and the crash occurs.

As stated by @Watcher3056 , i can't simply update my project to 2023 as its unstable.

Also i can't downgrade PAD to version 1.7.0 because i'm using other packages from Play Core (like in-app reviews) that uses Core 2.0.0, and conflicts with the version 1.10.0 used by PAD 1.7.0

**Comment by blazejhanzel** [comment]
Hey, I had similar problem with game crashing on startup when I want to use Google Play In-App Review. After few days of struggle I found out that crash occurs when I define `ReviewManager` inside the class this way:
```
private class ExampleClass
{
  private ReviewManager reviewManager = new();
}
```
but when I moved initialization to `Awake()`:
```
private class ExampleClass
{
  private ReviewManager reviewManager;

  private void Awake()
  {
    reviewManager = new();
  }
}
```
app doesn't crash anymore.

Hope this helps and I have a hope they will fix this or make an appropriate info on documentation because it's probable not the way how it should work.

**Comment by emathis11** [comment]
I upgraded to Unity 2022.3.4 and get the opposite problem, any version <= 1.7.0 causes a crash on launch with almost the same error message. So you may want to try updating to 2022.3 to work around your problem.

**Comment by julien-tamade** [comment]
Hi, we upgraded from 2019 to 2021 and are now getting the crash. The weird thing is we don't even use any google play service or have the plugin installed at all. Would love any thoughts on this

**Comment by devjta** [comment]
Yeah, we also face this issue and already wasted 3 days on that..

We dont integrate ANYWHERE this PAD. We dont USE it. We dont NEED it, as the filesize doesnt matter.

Why is that thing such a massive issue? 

When I look at the decompiled source, no one is refeering to the "gms.tasks.Task".. So its probably coming from some JNI related stuff.

How can I turn that crap off? Why is it including or want todo things on its own? Why did it work BETTER (using the Play-Core-Tasks, not the Play-Service-Task) in the previous version?

We have play-core added in the main app since ages and only after unity upgrade, we face that issue..

So on a newer unity version, you are somehow using an older implementation? WHY??

**Comment by SierraChica** [comment]
Finally working for me using:
- Unity 2022.3.4
- PAD 1.8.2

Unity issue tracker to follow:
https://issuetracker.unity3d.com/issues/android-regex-in-checkplaylibraryadded-incorrectly-identifies-play-core-common-libraries

**Comment by Trunksome** [comment]
Thank you, your post made me keep trying! And indeed I figured it out ... i think something broke during resolving of dependencies, I ended up removing all google plugins and trying it again. This time it worked. So it seems possible! I'm just wondering why it says minimum 2023 beta ... I actually migrated the project to that unity version and tried it, just to see if it would fix the problem (which ofc it didn't)

**Comment by roointan** [comment]
I'm Using Unity 2022.3.12f1 and app was crashing on start. Updating Google Play Review to version 1.8.1 fixed the issue for me.

**Comment by deniskutovskiy** [comment]
I'm using Unity 2020.3.36 and none of versions 1.7.0 - 1.8.2 helped me. Now I'm on my way to try update my project to 2022.3.

**Comment by firdiar-mita** [comment]
> I'm using Unity 2020.3.36f1 and none of versions 1.7.0 - 1.8.2 of Play Asset Delivery worked for me.

make sure to only use default compression for aab

**Comment by deniskutovskiy** [comment]
Finally, I was able to get it to work!
Switching versions to **Unity 2020.3.48f1** and **PAD 1.6.0** made the solution work for me on all Android versions, regardless of compression.

**Comment by aleter** [comment]
> Hi, In my case I 'm using Unity 2021.3.36f1, and I solved the problem updating package com.google.android.play:core-common to version 2.0.0, and com.google.android.play to 2.0.0, both in files "ProjectSettings/AndroidResolverDependencies.xml" and "Assets/Plugins/Android/mainTemplate.gradle"

can you provide your AndroidResolverDependencies.xml please

because i have only com.google.android.play:core-common dependency, but no com.google.android.play in AndroidResolverDependencies.xm

**Comment by zhaowhao** [comment]
Today, I fixed this issue with the following solution:
Comment out the following line:
`//implementation "com.google.android.play:core:1.10.0"`
Add the following line:
`implementation 'com.google.android.play:asset-delivery:2.2.2'`

The reason is likely that the latest version of Unity uses a method that is included in the new Play Asset Delivery library, which is not present in the old Play Core library.
For detailed migration information, you can refer to the following documentation:
https://developer.android.com/guide/playcore

**Comment by 1501432163** [comment]
> Finally, I was able to get it to work! Switching versions to **Unity 2020.3.48f1** and **PAD 1.6.0** made the solution work for me on all Android versions, regardless of compression.
> 
> So if I were anyone facing the problem, I'd look for a solution in finding a working match between Unity and PAD versions.

========================================================

Is this combination suitable for Android 14?

**Comment by Andrei-Lapusteanu** [comment]
We were using Unity `2021.3.27f1`, and were not able to upgrade to PAD versions any higher than `1.7.0`.
Upgrading to the latest LTS (as of writing), `2021.3.42f1`, got PAD `1.8.2` working without hard-crashing on app start, at least for our setup.

For context, we required this because we also needed to update to the latest `com.google.play.appupdate@1.8.2` as Android 14 requires the Play In-App Updates Library 2.1.0 (which is a dependency in `com.google.play.appupdate@1.8.2`), and we could **not** get PAD `1.7.0` working with `com.google.play.appupdate@1.8.2`.

**Comment by WeiLingQiang** [comment]
Has anyone solved this problem?
I am using Unity2021.3.33 and want to upgrade API34 to support Android14 version
So I need to upgrade the PAD version. Unfortunately, the crash as mentioned in the title also occurred

**Comment by denis-ftc-denisov** [comment]
Same problem here.
When using older PAD version, we got different crashes under API Level 34. 
But after upgrade we got this one.

**Comment by WeiLingQiang** [comment]
> Same problem here. When using older PAD version, we got different crashes under API Level 34. But after upgrade we got this one.

1.Play Asset Delivery (PAD) in the Google plugin required for AAB packages needs to be upgraded to v2.1.0 (May 2023) https://developer.android.com/reference/com/google/android/play/core/release-notes-asset_delivery
https://github.com/google/play-unity-plugins/commit/7295d55dd7a5a2db221870668410443c873366bf#diff-3e5b25ffcf2e225ac09627dac0a388ce08fec62b2365076b36a7d3e114412857R3
2.Due to the compatibility issues of the current Unity engine version (2021.3.33) with the new version of PAD https://github.com/google/play-unity-plugins/issues/187
3.The official has This issue is fixed in the new version 2021.3.41f1 https://unity.cn/release-notes/lts/2021/2021.3.41f1
